### ISSUE TITLE
Concern about the future of this addon

### ISSUE THREAD

**Issue by patcoll** [ember-launch-darkly/ember-launch-darkly#22]
Hey folks! I'm glad someone grabbed this repo and was able to secure apparently everything about it, including past issues, etc. I don't have any relationship with Kayako or any of its employees but the disappearance of its repos is concerning.

I lead a team that's just started to depend on this addon, and I wonder -- is there anything that can be done to help sustain it for the future? Does it need a new sponsor or a new home?

**Comment by achambers** [comment]
No need to be concerned dude. This is my focus right now. Play along at #36 😉
