### ISSUE TITLE
Update ember/ember-cli version

### ISSUE THREAD

**Issue by achambers** [ember-launch-darkly/ember-launch-darkly#25]
This addon is super out of date and it feels like upgrading the ember/ember-cli version might be a good starting point in updating things like the LD js client lib and fixing a few other anomalies.

Of the top of my head, a few things that are affected when updating the ember version are:

- The way the instance-initializer exposes the `ld` client on window
- The way `withVariation` helper should be used
- The way the test client should be used
- The ember-cli-shims imports need to be updated
- The babel transform needs to be updated to support the new imports

**Comment by achambers** [comment]
Hey @patcoll . Long time no speak mate. Are you still interested in being involved in this addon?

I'm just now trying to get some time to update some things that have been on my mind for ages. Are you interested in "rubber ducking" a few things with me?

**Comment by patcoll** [comment]
Sure @achambers — let’s do it! I can send you a note to set up a pairing session.

**Comment by achambers** [comment]
Will be handled by #36
